try {
    let a = 34;
    // console.log(a);
    //gives error
    console.log(b);
} catch (error) {
    // console.log(error.name);
    // console.log(error.message);
    console.log(error);
    console.log(bsdk);    //error
}
// if try and catch in the block exists errors the bellow code not run
// console.log("Done");


// finally block exucute always error are occured or not
finally {
    console.log("All The Best Guys");
}